### ISSUE TITLE
Key bindings for Mac...

### ISSUE THREAD

**Issue by DylanSunLei** [dotcypress/GitHubMarkdownPreview#22] opened 2015-10-22 17:52 UTC
I'm pretty new to this or sublime. I follow the installation and install this plugin for my sublime3. However, After I open the sublime3 and hit "ctrl+shift+g" or "cmd+shift+g". Neither of them works.

Could you please help me on this?

**Comment by thetypebeast** [comment] 2016-01-06 00:15
Possible Duplicate of Issue #13 ?

**Closed** 2016-05-18 21:14 UTC
